[package]
name = "turnkey_auth"
version = "0.0.0-alpha.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Wire-format and protocol support for Turnkey-backed authentication"
repository = "https://github.com/tkhq/rust-sdk"
homepage = "https://turnkey.com"

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
base64 = { workspace = true }
hex = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util", "macros", "net", "rt", "signal", "time"] }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
