[package]
name = "tk"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anstyle = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
hex = { workspace = true }
libc = { workspace = true }
rand_core = { workspace = true }
reqwest = { workspace = true }
rpassword = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
socket2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util", "macros", "net", "process", "rt-multi-thread", "signal", "time"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
turnkey_api_key_stamper = { workspace = true }
turnkey_auth = { workspace = true }
turnkey_client = { workspace = true }
turnkey_enclave_encrypt = { workspace = true }
uuid = { workspace = true }
zeroize = { workspace = true }

[build-dependencies]
sha2 = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
predicates = { workspace = true }
strum = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util", "macros", "net", "process", "rt-multi-thread", "sync", "time"] }
wiremock = { workspace = true }
